<?php
/**
 * Created by PhpStorm.
 * User: altisek
 * Date: 27.01.2017
 * Time: 8:27
 */

namespace AdminModule;

use Nette;

abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    protected $database;

    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        if($this->user->loggedIn)
        {

        }else{
            $this->flashMessage('Musíte se první přihlásit','danger');
            $this->redirect('Sign:in');
        }
    }
    public function __construct(Nette\Database\Context $database)
    {
        $this->database = $database;
    }
}